config/routes.rb
Rails.application.routes.draw do
  resources :map_data
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'map_data#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map_datum.rb
class MapDatum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/map_data_controller.rb
class MapDataController < ApplicationController
  require 'json'

  def index
    file = File.read('config/addresses.json')
    @data_hash = JSON.parse(file)
    @json = @data_hash["locations"]

    @test = @data_hash["locations"][0].values

    # if .save
    #   redirect_to new_map_datum_path()
    # end

    # render json: @test

  end

  # POST /map_data/new
  def create
    @address_1 = params['/map_data']['address_1']
    @address_2 = params['/map_data']['address_2']
    # binding.pry


    # file = File.read('config/addresses.json')
    # @data_hash = JSON.parse(file)
    # @json = @data_hash["locations"]
    # @test = @data_hash["locations"][0].values
    # redirect_to new_map_datum_path
  end

  def new

    file = File.read('config/addresses.json')
    @data_hash = JSON.parse(file)
    @json = @data_hash["locations"]
    # @data_hash["locations"].select {|x| x['id']==''}.first['number']d dd
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_data_helper.rb
module MapDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hoodq</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/map_data/_form.html.erb
<%= form_for(map_datum) do |f| %>
  <% if map_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map_datum.errors.count, "error") %> prohibited this map_datum from being saved:</h2>

      <ul>
      <% map_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :nearestCoffeeShop %>
    <%= f.text_field :nearestCoffeeShop %>
  </div>

  <div class="field">
    <%= f.label :workDistance %>
    <%= f.text_field :workDistance %>
  </div>

  <div class="field">
    <%= f.label :nearbyDogPark %>
    <%= f.text_field :nearbyDogPark %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/map_data/index.html.erb
<header>
  <div>
    <img src="images/hoodq-logo.png" id="logo">
    <div class="container">
      <h2 id="title">Address Comparison Prioritizer</h2>
    </div>
  </div>
</header>

<div id="priority-section">
  <section>
    <h4>What's Important to You?</h4>
    <br>
    <p id="desc">Drag &amp; Drop! &udarr;</p>
    <div class="container" id="priority">
      <div id="sortable-ul">
        <ul id="sortable">

          <li class="ui-state-default">Nearest Coffee Shop</li>
          <li class="ui-state-default">Work Distance</li>
          <li class="ui-state-default">Nearby Dog Park</li>
        </ul>
      </div>
    </div>
  <div class="container">
    <button id='prioritize_button' onClick="myFunction()">Prioritize!</button>
  </div>
  </section>
</div>

<%= form_for(map_data_path, html: { id: 'comparison_form' }) do |f| %>
<section>
  <div class="container">
    <div class="row">
      <!--  LIST #1 -->
      <div class="col-sm-6">
        <div class="form-group" id="form">
          <%= f.select(:address_1, id: 'first') do |x| %>
            <% @json.each do |address| %>
              <%= content_tag(:option, address['address'], data: {coffee: address["nearestCoffeeShop"], work: address["workDistance"], dogpark: address["nearbyDogPark"] }) %>
            <% end %>
          <% end %>
        </div> <!-- form-group -->
      </div> <!-- col -->

      <!--  LIST #2 -->
      <div class="col-sm-6">
        <div class="form-group" id="form">
          <%= f.select(:address_2, id: 'second') do |x| %>
            <% @json.each do |address| %>
              <%= content_tag(:option, address['address'], data: {coffee: address["nearestCoffeeShop"], work: address["workDistance"], dogpark: address["nearbyDogPark"] }) %>
            <% end %>
          <% end %>
        </div> <!-- form-group -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
      <%= f.submit 'Compare!', id: 'compare_button' %>
</section>
<% end %>

<div id="compare-boxes">
<section class="pricing" id="PRICING">
<div class="container">
    <div class="row flat_price">
        <div class="col-sm-6">
            <ul id='selection_1' class="plan wow fadeInUp animated" data-wow-duration="500ms">
                <li class="plan-name">
                    PICK #1
                </li>
                <li class="plan-price">
                    <strong class="price">Address</strong>
                </li>
                <li class="coffee">
                    Nearest Coffee Shop:
                </li>
                <li class="work">
                    Work Distance:
                </li>
                <li class="dog">
                    Nearby Dog Park:
                </li>
                <br>
            </ul>
        </div>

        <div class="col-sm-6">
            <ul id='selection_2' class="plan wow fadeInUp animated" data-wow-duration="500ms" data-wow-delay="300ms">
                <li class="plan-name">
                    PICK #2
                </li>
                <li class="plan-price">
                    <strong class="price">Address</strong>
                </li>

                <li class='coffee'>
                    Nearest Coffee Shop:
                </li>
                <li class="work">
                    Work Distance:
                </li>
                <li class="dog">
                    Nearby Dog Park:
                </li>
                <br>
            </ul>
        </div>
    </div><!-- END ROW -->
</div><!-- END CONTAINER -->
</section>
</div>


<footer>
  <div>
    <img src="images/neighbourhood.png" id="neighbourhood">
  </div>
</footer>

app/views/map_data/new.html.erb
<section class="pricing" id="PRICING">
<div class="container">
    <div class="row flat_price">
        <div class="col-sm-6">
            <ul class="plan wow fadeInUp animated" data-wow-duration="500ms">
                <li class="plan-name">
                    PICK #1
                </li>
                <li class="plan-price">
                    <strong class="price">Address</strong>
                </li>
                <li>
                    Nearest Coffee Shop:
                </li>
                <li>
                    Work Distance:
                </li>
              
                <li>
                    Nearby Dog Park:
                </li>
            </ul>
        </div>

        <div class="col-sm-6">
            <ul class="plan wow fadeInUp animated" data-wow-duration="500ms" data-wow-delay="300ms">
                <li class="plan-name">
                    PICK #2
                </li>
                <li class="plan-price">
                    <strong class="price">Address</strong>
                </li>
                <li>
                    Nearest Coffee Shop:
                </li>
                <li>
                    Work Distance:
                </li>
                <li>
                    Nearby Dog Park:
                </li>
            </ul>
        </div>
    </div><!-- END ROW -->
</div><!-- END CONTAINER -->
</section>